create table Services (
serviceID integer primary key not null,
agencyID integer not null constraint fk_serAgencyID references Agency (agencyID),
shortName varchar(50) not null,
longName varchar(300) not null,
type integer not null
);

insert into Services values (1,2,'1','Ligne 1 - Verte',1);
insert into Services values (2,2,'2','Ligne 2 - Orange',1);
insert into Services values (3,2,'4','Ligne 4 - Jaune',1);
insert into Services values (4,2,'5','Ligne 5 - Bleue',1);
insert into Services values (5,2,'10','De Lorimier',3);
insert into Services values (6,2,'11','Parc-du-Mont-Royal / Ridgewood',3);
insert into Services values (7,2,'12','Île-des-Soeurs',3);
insert into Services values (8,2,'13','Christophe-Colomb',3);
insert into Services values (9,2,'14','Atateken',3);
insert into Services values (10,2,'15','Sainte-Catherine',3);
insert into Services values (11,2,'16','Graham',3);
insert into Services values (12,2,'17','Décarie',3);
insert into Services values (13,2,'18','Beaubien',3);
insert into Services values (14,2,'19','Chabanel / Marché Central',3);
insert into Services values (15,2,'22','Notre-Dame',3);
insert into Services values (16,2,'24','Sherbrooke',3);
insert into Services values (17,2,'25','Angus',3);
insert into Services values (18,2,'26','Mercier-Est',3);
insert into Services values (19,2,'27','Boulevard Saint-Joseph',3);
insert into Services values (20,2,'28','Honoré-Beaugrand',3);
insert into Services values (21,2,'29','Rachel',3);
insert into Services values (22,2,'30','Saint-Denis / Saint-Hubert',3);
insert into Services values (23,2,'31','Saint-Denis',3);
insert into Services values (24,2,'32','Lacordaire',3);
insert into Services values (25,2,'33','Langelier',3);
insert into Services values (26,2,'34','Sainte-Catherine',3);
insert into Services values (27,2,'35','Griffintown',3);
insert into Services values (28,2,'36','Monk',3);
insert into Services values (29,2,'37','Jolicoeur',3);
insert into Services values (30,2,'39','Des Grandes-Prairies',3);
insert into Services values (31,2,'40','Henri-Bourassa-Est',3);
insert into Services values (32,2,'41','Quartier Saint-Michel / Ahuntsic',3);
insert into Services values (33,2,'43','Monselet',3);
insert into Services values (34,2,'44','Armand-Bombardier',3);
insert into Services values (35,2,'45','Papineau',3);
insert into Services values (36,2,'46','Casgrain',3);
insert into Services values (37,2,'47','Masson',3);
insert into Services values (38,2,'48','Perras',3);
insert into Services values (39,2,'49','Maurice-Duplessis',3);
insert into Services values (40,2,'51','Édouard-Montpetit',3);
insert into Services values (41,2,'52','de Liège',3);
insert into Services values (42,2,'54','Charland / Chabanel',3);
insert into Services values (43,2,'55','Boulevard Saint-Laurent',3);
insert into Services values (44,2,'56','Saint-Hubert',3);
insert into Services values (45,2,'57','Pointe-Saint-Charles',3);
insert into Services values (46,2,'58','Wellington',3);
insert into Services values (47,2,'61','Wellington',3);
insert into Services values (48,2,'63','Girouard',3);
insert into Services values (49,2,'64','Grenet',3);
insert into Services values (50,2,'66','The Boulevard',3);
insert into Services values (51,2,'67','Saint-Michel',3);
insert into Services values (52,2,'68','Pierrefonds',3);
insert into Services values (53,2,'69','Gouin',3);
insert into Services values (54,2,'70','Bois-Franc',3);
insert into Services values (55,2,'71','Du Centre',3);
insert into Services values (56,2,'72','Alfred-Nobel',3);
insert into Services values (57,2,'73','Dalton',3);
insert into Services values (58,2,'74','Bridge',3);
insert into Services values (59,2,'75','De la Commune',3);
insert into Services values (60,2,'78','Laurendeau',3);
insert into Services values (61,2,'80','Avenue du Parc',3);
insert into Services values (62,2,'81','Saint-Jean-Baptiste',3);
insert into Services values (63,2,'85','Hochelaga',3);
insert into Services values (64,2,'86','Pointe-aux-Trembles',3);
insert into Services values (65,2,'90','Saint-Jacques',3);
insert into Services values (66,2,'92','Jean-Talon Ouest',3);
insert into Services values (67,2,'93','Jean-Talon',3);
insert into Services values (68,2,'94','D''Iberville',3);
insert into Services values (69,2,'95','Bélanger',3);
insert into Services values (70,2,'97','Avenue-du-Mont-Royal',3);
insert into Services values (71,2,'99','Villeray',3);
insert into Services values (72,2,'100','Crémazie',3);
insert into Services values (73,2,'101','Saint-Patrick',3);
insert into Services values (74,2,'102','Somerled',3);
insert into Services values (75,2,'103','Monkland',3);
insert into Services values (76,2,'104','Cavendish',3);
insert into Services values (77,2,'105','Sherbrooke',3);
insert into Services values (78,2,'106','Newman',3);
insert into Services values (79,2,'107','Verdun',3);
insert into Services values (80,2,'108','Bannantyne',3);
insert into Services values (81,2,'109','Boulevard Shevchenko',3);
insert into Services values (82,2,'110','Centrale',3);
insert into Services values (83,2,'112','Airlie',3);
insert into Services values (84,2,'113','Lapierre',3);
insert into Services values (85,2,'115','Paré',3);
insert into Services values (86,2,'116','Lafleur / Norman',3);
insert into Services values (87,2,'117','O''Brien',3);
insert into Services values (88,2,'119','Rockland',3);
insert into Services values (89,2,'121','Sauvé / Côte-Vertu',3);
insert into Services values (90,2,'123','Dollard',3);
insert into Services values (91,2,'124','Victoria',3);
insert into Services values (92,2,'125','Ontario',3);
insert into Services values (93,2,'126','Thimens / Grenet',3);
insert into Services values (94,2,'128','Saint-Laurent',3);
insert into Services values (95,2,'129','Côte-Sainte-Catherine',3);
insert into Services values (96,2,'131','De l''Assomption',3);
insert into Services values (97,2,'135','De l''Esplanade',3);
insert into Services values (98,2,'136','Viau',3);
insert into Services values (99,2,'138','Notre-Dame-de-Grâce',3);
insert into Services values (100,2,'139','Pie-IX',3);
insert into Services values (101,2,'140','Fleury',3);
insert into Services values (102,2,'141','Jean-Talon Est',3);
insert into Services values (103,2,'144','Avenue des Pins',3);
insert into Services values (104,2,'146','Christophe-Colomb / Meilleur',3);
insert into Services values (105,2,'150','René-Lévesque',3);
insert into Services values (106,2,'160','Barclay',3);
insert into Services values (107,2,'161','Van Horne',3);
insert into Services values (108,2,'162','Westminster',3);
insert into Services values (109,2,'164','Dudemaine',3);
insert into Services values (110,2,'165','Côte-des-Neiges',3);
insert into Services values (111,2,'166','Queen-Mary',3);
insert into Services values (112,2,'168','Citè-du-Havre',3);
insert into Services values (113,2,'170','Keller',3);
insert into Services values (114,2,'171','Henri-Bourassa',3);
insert into Services values (115,2,'172','Du Golf',3);
insert into Services values (116,2,'174','Côte-Vertu-Ouest',3);
insert into Services values (117,2,'175','Griffith / Saint-François',3);
insert into Services values (118,2,'176','Berlioz',3);
insert into Services values (119,2,'177','Thimens',3);
insert into Services values (120,2,'179','De l''Acadie',3);
insert into Services values (121,2,'180','De Salaberry',3);
insert into Services values (122,2,'183','Gouin Est',3);
insert into Services values (123,2,'185','Sherbrooke',3);
insert into Services values (124,2,'186','Sherbrooke-Est',3);
insert into Services values (125,2,'187','René-Lévesque',3);
insert into Services values (126,2,'188','Couture',3);
insert into Services values (127,2,'189','Notre-Dame',3);
insert into Services values (128,2,'191','Broadway / Provost',3);
insert into Services values (129,2,'192','Robert',3);
insert into Services values (130,2,'193','Jarry',3);
insert into Services values (131,2,'195','Sherbrooke / Notre-Dame',3);
insert into Services values (132,2,'196','Parc-Industriel-Lachine',3);
insert into Services values (133,2,'197','Rosemont',3);
insert into Services values (134,2,'200','Sainte-Anne-de-Bellevue',3);
insert into Services values (135,2,'201','Saint-Charles / Saint-Jean',3);
insert into Services values (136,2,'202','Dawson',3);
insert into Services values (137,2,'203','Carson',3);
insert into Services values (138,2,'204','Cardinal',3);
insert into Services values (139,2,'205','Gouin',3);
insert into Services values (140,2,'206','Roger-Pilon',3);
insert into Services values (141,2,'207','Jacques-Bizard',3);
insert into Services values (142,2,'208','Brunswick',3);
insert into Services values (143,2,'209','Des Sources',3);
insert into Services values (144,2,'211','Bord-du-Lac',3);
insert into Services values (145,2,'212','Sainte-Anne',3);
insert into Services values (146,2,'213','Parc-Industriel-Saint-Laurent',3);
insert into Services values (147,2,'215','Henri-Bourassa',3);
insert into Services values (148,2,'216','Transcanadienne',3);
insert into Services values (149,2,'217','Anse-à -l''Orme',3);
insert into Services values (150,2,'218','Antoine-Faucon',3);
insert into Services values (151,2,'219','Chemin Sainte-Marie',3);
insert into Services values (152,2,'220','Kieran',3);
insert into Services values (153,2,'225','Hymus',3);
insert into Services values (154,2,'350','Verdun / LaSalle',3);
insert into Services values (155,2,'353','Lacordaire / Maurice-Duplessis',3);
insert into Services values (156,2,'354','Sainte-Anne-de-Bellevue / Centre-ville',3);
insert into Services values (157,2,'355','Pie-IX',3);
insert into Services values (158,2,'356','Lachine / YUL Aéroport / Des Sources',3);
insert into Services values (159,2,'357','Saint-Michel',3);
insert into Services values (160,2,'358','Sainte-Catherine',3);
insert into Services values (161,2,'359','Papineau',3);
insert into Services values (162,2,'360','Avenue des Pins',3);
insert into Services values (163,2,'361','Saint-Denis',3);
insert into Services values (164,2,'362','Hochelaga / Notre-Dame',3);
insert into Services values (165,2,'363','Boulevard Saint-Laurent',3);
insert into Services values (166,2,'364','Sherbrooke / Joseph-Renaud',3);
insert into Services values (167,2,'365','Avenue du Parc',3);
insert into Services values (168,2,'368','Avenue-du-Mont-Royal',3);
insert into Services values (169,2,'369','Côte-des-Neiges',3);
insert into Services values (170,2,'370','Rosemont',3);
insert into Services values (171,2,'371','Décarie',3);
insert into Services values (172,2,'372','Jean-Talon',3);
insert into Services values (173,2,'376','Pierrefonds / Centre-ville',3);
insert into Services values (174,2,'378','Sauvé / YUL Aéroport',3);
insert into Services values (175,2,'380','Henri-Bourassa',3);
insert into Services values (176,2,'382','Pierrefonds / Saint-Charles',3);
insert into Services values (177,2,'401','Express Saint-Charles',3);
insert into Services values (178,2,'405','Express Bord-du-Lac',3);
insert into Services values (179,2,'406','Express Newman',3);
insert into Services values (180,2,'407','Express Île-Bizard',3);
insert into Services values (181,2,'409','Express Des Sources',3);
insert into Services values (182,2,'410','Express Notre-Dame',3);
insert into Services values (183,2,'411','Express Lionel-Groulx',3);
insert into Services values (184,2,'419','Express John Abbott',3);
insert into Services values (185,2,'420','Express Notre-Dame-de-Grâce',3);
insert into Services values (186,2,'425','Express Anse-à -l''Orme',3);
insert into Services values (187,2,'427','Express Saint-Joseph',3);
insert into Services values (188,2,'428','Express Parcs industriels de l''Est',3);
insert into Services values (189,2,'430','Express Pointe-aux-Trembles',3);
insert into Services values (190,2,'432','Express Lacordaire',3);
insert into Services values (191,2,'439','Express Pie-IX',3);
insert into Services values (192,2,'440','Express Charleroi',3);
insert into Services values (193,2,'444','Express Cégep Marie-Victorin',3);
insert into Services values (194,2,'445','Express Papineau',3);
insert into Services values (195,2,'448','Express Maurice-Duplessis',3);
insert into Services values (196,2,'449','Express Rivière-des-Prairies',3);
insert into Services values (197,2,'460','Express Métropolitaine',3);
insert into Services values (198,2,'465','Express Côte-des-Neiges',3);
insert into Services values (199,2,'467','Express Saint-Michel',3);
insert into Services values (200,2,'468','Express Pierrefonds / Gouin',3);
insert into Services values (201,2,'469','Express Henri-Bourassa',3);
insert into Services values (202,2,'470','Express Pierrefonds',3);
insert into Services values (203,2,'475','Express Dollard-des-Ormeaux',3);
insert into Services values (204,2,'480','Express du Parc',3);
insert into Services values (205,2,'485','Express Antoine-Faucon',3);
insert into Services values (206,2,'486','Express Sherbrooke',3);
insert into Services values (207,2,'487','Express Bout-de-l''Île',3);
insert into Services values (208,2,'491','Express Lachine',3);
insert into Services values (209,2,'495','Express Lachine / LaSalle',3);
insert into Services values (210,2,'496','Express Victoria',3);
insert into Services values (211,2,'711','Parc-du-Mont-Royal / Oratoire',3);
insert into Services values (212,2,'715','Vieux-Montréal / Vieux-Port',3);
insert into Services values (213,2,'747','YUL Aèroport  / Centre-Ville',3);
insert into Services values (214,2,'767','La Ronde / Station Jean-Drapeau',3);
insert into Services values (215,2,'769','La Ronde / Station Papineau',3);
insert into Services values (216,2,'777','Jean-Drapeau / Casino / Bonaventure',3);
insert into Services values (217,2,'811','Navette Services santé',3);
insert into Services values (218,2,'822','Navette Longue-Pointe',3);
insert into Services values (219,2,'872','Île-des-Soeurs',3);
insert into Services values (220,2,'874','Robert-Bourassa',3);
insert into Services values (221,2,'968','Trainbus Roxboro / Côte-Vertu',3);
insert into Services values (222,3,'VH','11 - Vaudreuil/Hudson',2);
insert into Services values (223,3,'SH','13 - Mont-Saint-Hilaire',2);
insert into Services values (224,3,'SJ','12 - Saint-Jérôme',2);
insert into Services values (225,3,'CA','14 - Candiac',2);
insert into Services values (226,3,'MA','15 - Mascouche',2);
insert into Services values (227,3,'CITHSL-111','Haut-Saint-Laurent',3);
insert into Services values (228,3,'CITHSL-140','Mercier - Châteauguay - Mercier',3);
insert into Services values (229,3,'CITCRC-104','Chambly (Brassard - Martel - Gentilly)',3);
insert into Services values (230,3,'CITCRC-105','Chambly - Richelieu - Marieville',3);
insert into Services values (231,3,'CITCRC-106','Chambly (Brassard - Salaberry - Gentilly)',3);
insert into Services values (232,3,'CITCRC-107','Chambly (Anne-Le Seigneur - Salaberry - Brassard)',3);
insert into Services values (233,3,'CITCRC-481','Chambly - Terminus Brossard',3);
insert into Services values (234,3,'CITCRC-482','Chambly (Franquet - Fréchette) - Terminus Brossard',3);
insert into Services values (235,3,'CITCRC-483','Carignan (Bellerive-Henriette) - Terminus Brossard',3);
insert into Services values (236,3,'CITCRC-484','Carignan (Île aux Lièvres) - Terminus Brossard',3);
insert into Services values (237,3,'CITCRC-485','Chambly (Lebel - Fréchette) - Terminus Brossard',3);
insert into Services values (238,3,'CITCRC-486','Marieville - Terminus Brossard',3);
insert into Services values (239,3,'CITCRC-487','Chambly (Industriel) - Terminus Brossard',3);
insert into Services values (240,3,'CITCRC-488','Chambly (Daigneault - Martel) - Terminus Brossard',3);
insert into Services values (241,3,'CITCRC-680','Chambly - Terminus Longueuil',3);
insert into Services values (242,3,'CITCRC-681','Chambly - Terminus Longueuil - Cégep É.-Montpetit',3);
insert into Services values (243,3,'CITCRC-685','Carignan - Chambly - Saint-Jean-sur-Richelieu',3);
insert into Services values (244,3,'CITLA-100','Saint-Jérôme - secteur Bellefeuille sud',3);
insert into Services values (245,3,'CITLA-101','Saint-Jérôme - secteur Saint-Antoine',3);
insert into Services values (246,3,'CITLA-102','Saint-Jérôme - secteur Lafontaine',3);
insert into Services values (247,3,'CITLA-103','Saint-Jérôme - secteur Centre',3);
insert into Services values (248,3,'CITLA-105','Saint-Jérôme - secteur Bellefeuille nord',3);
insert into Services values (249,3,'CITLA-107','Saint-Jérôme - Bellefeuille sud (Lajeunesse)',3);
insert into Services values (250,3,'CITLA-11','Laval - Rosemère - Sainte-Thérèse',3);
insert into Services values (251,3,'CITLA-12','Direction Bois-des-Filion',3);
insert into Services values (252,3,'CITLA-15','Rosemère - Gare Rosemère',3);
insert into Services values (253,3,'CITLA-17','Terrebonne - Gare Rosemère',3);
insert into Services values (254,3,'CITLA-20','Terrebonne ouest - Gare Rosemère',3);
insert into Services values (255,3,'CITLA-22','Bois-des-Filion - Sainte-Thérèse',3);
insert into Services values (256,3,'CITLA-23','Sainte-Anne-des-Plaines - Sainte-Thérèse',3);
insert into Services values (257,3,'CITLA-24','Sainte-Anne-des-Plaines - Laval (métro Cartier)',3);
insert into Services values (258,3,'CITLA-243','Saint-Augustin - Sainte-Thérèse',3);
insert into Services values (259,3,'CITLA-27','Lorraine - Sainte-Thérèse',3);
insert into Services values (260,3,'CITLA-28','Terrebonne - Laval (métro Cartier)',3);
insert into Services values (261,3,'CITLA-404','Service Express Centre-Ville/Deux-Montagnes',3);
insert into Services values (262,3,'CITLA-496','Navette Deux-Montagnes - Sunnybrooke',3);
insert into Services values (263,3,'CITLA-498','St-Eustache - Ste-Dorothée - Centre-ville',3);
insert into Services values (264,3,'CITLA-499','Service Express Côte-Vertu / Deux-Montagnes',3);
insert into Services values (265,3,'CITLA-51','Boisbriand Nord vers Boisbriand Sud',3);
insert into Services values (266,3,'CITLA-52','Boisbriand Sud vers Boisbriand Nord',3);
insert into Services values (267,3,'CITLA-59','Boisbriand - Laval (mÃ©tro Montmorency)',3);
insert into Services values (268,3,'CITLA-60','Sainte-Thérèse',3);
insert into Services values (269,3,'CITLA-61','Sainte-Thérèse - secteur Bas Sainte-Thérèse',3);
insert into Services values (270,3,'CITLA-62','Sainte-Thérèse - secteur des Mille-Îles',3);
insert into Services values (271,3,'CITLA-71','Blainville - secteur est',3);
insert into Services values (272,3,'CITLA-72','Blainville - secteur ouest',3);
insert into Services values (273,3,'CITLA-73','Blainville - secteur Fontainebleau',3);
insert into Services values (274,3,'CITLA-74','Blainville - secteur Fontainebleau',3);
insert into Services values (275,3,'CITLA-744','Express d''Oka',3);
insert into Services values (276,3,'CITLA-8','Saint-Eustache - Laval (métro Montmorency)',3);
insert into Services values (277,3,'CITLA-80','Saint-Eustache - Pointe-Calumet',3);
insert into Services values (278,3,'CITLA-81','Saint-Eustache - Pointe-Calumet',3);
insert into Services values (279,3,'CITLA-88','Saint-Eustache - Sainte-Thérèse',3);
insert into Services values (280,3,'CITLA-89','Saint-Eustache - secteur Dubois',3);
insert into Services values (281,3,'CITLA-9','Saint-Jérôme - Laval',3);
insert into Services values (282,3,'CITLA-90','Saint-Eustache - Arthur-Sauvé et Industriel',3);
insert into Services values (283,3,'CITLA-904','Gare Deux-Montagnes - Grand-Moulin',3);
insert into Services values (284,3,'CITLA-91','Saint-Eustache - secteur est (Saint-Laurent)',3);
insert into Services values (285,3,'CITLA-92','Saint-Eustache - secteur centre',3);
insert into Services values (286,3,'CITLA-93','Saint-Eustache - Deux-Montagnes',3);
insert into Services values (287,3,'CITPI-1','Gare Vaudreuil/Parc Industriel/Seigneurie',3);
insert into Services values (288,3,'CITPI-10','Gare Vaudreuil/Auto-Plaza-Brunswick',3);
insert into Services values (289,3,'CITPI-115','Gare Vaudreuil / Dorion (Av. de la Fabrique)',3);
insert into Services values (290,3,'CITPI-15','Gare Vaudreuil / Gare Dorion via Valois  P-G-L',3);
insert into Services values (291,3,'CITPI-2','Gare Vaudreuil/Bourget/des Sarcelles',3);
insert into Services values (292,3,'CITPI-21','Gare Vaudreuil/Hudson/St-Charles',3);
insert into Services values (293,3,'CITPI-3','Gare Dorion/Valois/Tonnancour',3);
insert into Services values (294,3,'CITPI-31','Gare Pincourt T-V/Cardinal-Léger',3);
insert into Services values (295,3,'CITPI-33','Gare Pincourt T-V/Forest',3);
insert into Services values (296,3,'CITPI-335','Gare Pincourt T-V/Ste-Anne-de-Bellevue',3);
insert into Services values (297,3,'CITPI-35','Dorion / Ste-Anne-de-Bellevue via l''Île Perrot',3);
insert into Services values (298,3,'CITPI-4','Gare Vaudreuil/Ouimet/Floralies',3);
insert into Services values (299,3,'CITPI-40','Express Vaudreuil - Terminus Côte-Vertu',3);
insert into Services values (300,3,'CITPI-41','Gare Île-Perrot/Boishatel/Perrier/F. Cuillerier',3);
insert into Services values (301,3,'CITPI-42','Gare Île-Perrot / des Érables / Lucien-Manning',3);
insert into Services values (302,3,'CITPI-43','Gare Île-Perrot/Perrot/Rivelaine',3);
insert into Services values (303,3,'CITPI-44','Gares Pincourt/T-V Ile-Perrot / John-Abbott',3);
insert into Services values (304,3,'CITPI-45','Virginie-Roy / Ste-Anne-De-Bellevue',3);
insert into Services values (305,3,'CITPI-46','Gare Île-Perrot/Don Quichotte/Pointe-du-Domaine',3);
insert into Services values (306,3,'CITPI-47','Perrot/Caza/Pointe-du-Domaine',3);
insert into Services values (307,3,'CITPI-5','Gare Vaudreuil/Gare Dorion',3);
insert into Services values (308,3,'CITPI-51','Gare Vaudreuil / Saint-Lazare',3);
insert into Services values (309,3,'CITPI-6','Gare Vaudreuil/CSSS/du Ruisselet/Émile-Bouchard',3);
insert into Services values (310,3,'CITPI-61','Gare Vaudreuil/Rigaud',3);
insert into Services values (311,3,'CITPI-7','Gare Vaudreuil/John Abbott/Pointe-Claire',3);
insert into Services values (312,3,'CITPI-8','Gare Dorion/Chicoine/St-Antoine',3);
insert into Services values (313,3,'CITPI-9','Gare Vaudreuil/Gare Dorion/Marier',3);
insert into Services values (314,3,'CITPI-91','Gérald-Godin / Pointe-Claire',3);
insert into Services values (315,3,'CITLR-11','Saint-Philippe',3);
insert into Services values (316,3,'CITLR-123','Grand-Boisé - Montréal',3);
insert into Services values (317,3,'CITLR-124','La Clairière - Montréal',3);
insert into Services values (318,3,'CITLR-21','Vieux La Prairie',3);
insert into Services values (319,3,'CITLR-22','La Magdeleine',3);
insert into Services values (320,3,'CITLR-23','Grand-Boisé',3);
insert into Services values (321,3,'CITLR-230','La Prairie - Dix30',3);
insert into Services values (322,3,'CITLR-25','Symbiocité',3);
insert into Services values (323,3,'CITLR-28','La Prairie',3);
insert into Services values (324,3,'CITLR-29','La Prairie',3);
insert into Services values (325,3,'CITLR-31','Jean-Leman',3);
insert into Services values (326,3,'CITLR-32','Deauville',3);
insert into Services values (327,3,'CITLR-321','La Prairie - Montréal (Express)',3);
insert into Services values (328,3,'CITLR-323','Candiac - Montréal (Express)',3);
insert into Services values (329,3,'CITLR-33','Champlain',3);
insert into Services values (330,3,'CITLR-340','Candiac - La Prairie - Longueuil',3);
insert into Services values (331,3,'CITLR-341','La Prairie - Longueuil',3);
insert into Services values (332,3,'CITLR-343','Candiac - Longueuil',3);
insert into Services values (333,3,'CITLR-38','Candiac',3);
insert into Services values (334,3,'CITLR-39','Candiac',3);
insert into Services values (335,3,'CITROUS-100','Express Montréal',3);
insert into Services values (336,3,'CITROUS-130','Express Montréal via Principale',3);
insert into Services values (337,3,'CITROUS-200','Express Lasalle',3);
insert into Services values (338,3,'CITROUS-210','Express Longueuil',3);
insert into Services values (339,3,'CITROUS-30','Delson - Saint-Constant - Sainte-Catherine',3);
insert into Services values (340,3,'CITROUS-31','Jogues - Marie-Victorin - Saint-Laurent',3);
insert into Services values (341,3,'CITROUS-32','Brébeuf - Écluses - Jogues',3);
insert into Services values (342,3,'CITROUS-33','Central - Mason - Gare Sainte-Catherine',3);
insert into Services values (343,3,'CITROUS-34','Saint-Pierre - Monchamp - Sainte-Catherine',3);
insert into Services values (344,3,'CITROUS-35','Gare Saint-Constant - de l''Église - Beauvais',3);
insert into Services values (345,3,'CITROUS-36','Gare Delson - des Roitelets',3);
insert into Services values (346,3,'CITROUS-37','Principale - des Cascades - des Écluses',3);
insert into Services values (347,3,'CITROUS-38','Gare Sainte-Catherine',3);
insert into Services values (348,3,'CITROUS-40','Sainte-Catherine - Monchamp - de la Mairie',3);
insert into Services values (349,3,'CITROUS-43','Sainte-Catherine - Montée Saint-Régis',3);
insert into Services values (350,3,'CITSV-370','Saint-Amable - Sainte-Julie',3);
insert into Services values (351,3,'CITSV-532','Express Varennes / Radisson',3);
insert into Services values (352,3,'CITSV-700','Sorel-Tracy - Longueuil',3);
insert into Services values (353,3,'CITSV-701','Contrecoeur - Longueuil',3);
insert into Services values (354,3,'CITSV-707','Contrecoeur - Varennes (Jean-Coutu) - Longueuil',3);
insert into Services values (355,3,'CITSV-709','Contrecoeur - Longueuil',3);
insert into Services values (356,3,'CITSV-710','Verchères - Longueuil',3);
insert into Services values (357,3,'CITSV-720','Varennes - Longueuil',3);
insert into Services values (358,3,'CITSV-721','Varennes - Longueuil',3);
insert into Services values (359,3,'CITSV-722','Varennes - Longueuil',3);
insert into Services values (360,3,'CITSV-723','Varennes (IREQ) - Longueuil',3);
insert into Services values (361,3,'CITSV-730','Saint-Amable - Longueuil',3);
insert into Services values (362,3,'CITSV-731','Saint-Amable - Longueuil',3);
insert into Services values (363,3,'CITSV-732','Saint-Amable - Longueuil',3);
insert into Services values (364,3,'CITSV-733','Saint-Amable - Longueuil (Express)',3);
insert into Services values (365,3,'CITSO-1','Valleyfield - Beauharnois - Châteauguay - Montréal',3);
insert into Services values (366,3,'CITSO-20','Beauharnois',3);
insert into Services values (367,3,'CITSO-21','Châteauguay - Montréal',3);
insert into Services values (368,3,'CITSO-22','Châteauguay',3);
insert into Services values (369,3,'CITSO-23','Châteauguay - Montréal',3);
insert into Services values (370,3,'CITSO-24','Châteauguay',3);
insert into Services values (371,3,'CITSO-25','Châteauguay - Montréal',3);
insert into Services values (372,3,'CITSO-26','Châteauguay - Montréal',3);
insert into Services values (373,3,'CITSO-27','Châteauguay',3);
insert into Services values (374,3,'CITSO-28','Châteauguay - Montréal (Centre-Ville)',3);
insert into Services values (375,3,'CITSO-29','Châteauguay',3);
insert into Services values (376,3,'CITSO-31','Châteauguay - Montréal',3);
insert into Services values (377,3,'CITSO-32','Châteauguay - Montréal',3);
insert into Services values (378,3,'CITSO-33','Châteauguay',3);
insert into Services values (379,3,'CITSO-90','Cégep André-Laurendeau',3);
insert into Services values (380,3,'CITSO-98','Kahnawake - Montréal',3);
insert into Services values (381,3,'CITVR-12','Otterburn Park',3);
insert into Services values (382,3,'CITVR-200','Saint-Hyacinthe - Longueuil',3);
insert into Services values (383,3,'CITVR-201','ExpressO - Mont-Saint-Hilaire - Longueuil',3);
insert into Services values (384,3,'CITVR-20B','Beloeil',3);
insert into Services values (385,3,'CITVR-21','Mont-Saint-Hilaire (La Pommeraie)',3);
insert into Services values (386,3,'CITVR-22','Mont-Saint-Hilaire (des Patriotes)',3);
insert into Services values (387,3,'CITVR-23','Otterburn Park',3);
insert into Services values (388,3,'CITVR-24','Saint-Basile-le-Grand (sud)',3);
insert into Services values (389,3,'CITVR-25','Saint-Hyacinthe - Mont-Saint-Hilaire',3);
insert into Services values (390,3,'CITVR-26','Saint-Basile-le-Grand (nord)',3);
insert into Services values (391,3,'CITVR-30','Sainte-Julie - Saint-Hyacinthe',3);
insert into Services values (392,3,'CITVR-300','Saint-Hyacinthe - Terminus Brossard',3);
insert into Services values (393,3,'CITVR-520','Express Beloeil / Radisson',3);
insert into Services values (394,3,'MRCLASSO-1','Repentigny secteur Nord - Cégep',3);
insert into Services values (395,3,'MRCLASSO-100','L''Assomption-Repentigny-Charlemagne-Montréal',3);
insert into Services values (396,3,'MRCLASSO-11','Repentigny secteur Le Gardeur - Cégep',3);
insert into Services values (397,3,'MRCLASSO-14','L''Assomption - Repentigny-Le Gardeur - Charlemagne',3);
insert into Services values (398,3,'MRCLASSO-15','Repentigny secteur sud (rue Notre-Dame)',3);
insert into Services values (399,3,'MRCLASSO-2','Repentigny - Saint-Sulpice - Lavaltrie',3);
insert into Services values (400,3,'MRCLASSO-200','Express Repentigny - Montréal',3);
insert into Services values (401,3,'MRCLASSO-300','Repentigny - Montréal via Notre-Dame',3);
insert into Services values (402,3,'MRCLASSO-400','Repentigny - Montréal via Sherbrooke',3);
insert into Services values (403,3,'MRCLASSO-5','Navette gare Repentigny',3);
insert into Services values (404,3,'MRCLASSO-6','L''Épiphanie - L''Assomption',3);
insert into Services values (405,3,'MRCLASSO-8','Repentigny secteur Centre - Cégep',3);
insert into Services values (406,3,'MRCLASSO-9','Charlemagne - CHPLG - Terrebonne',3);
insert into Services values (407,3,'MRCLM-1','Terrebonne - Mascouche',3);
insert into Services values (408,3,'MRCLM-11','Terrebonne - Lachenaie',3);
insert into Services values (409,3,'MRCLM-11C','Terrebonne - Cité du sport - Lachenaie',3);
insert into Services values (410,3,'MRCLM-14','Terrebonne - La Plaine',3);
insert into Services values (411,3,'MRCLM-140','Lachenaie - Gare de Terrebonne - Terminus Radisson',3);
insert into Services values (412,3,'MRCLM-17','Terrebonne - La Plaine',3);
insert into Services values (413,3,'MRCLM-18','Terrebonne - Cité du sport - Cégep de Terrebonne',3);
insert into Services values (414,3,'MRCLM-19','Terrebonne - Terminus Montmorency',3);
insert into Services values (415,3,'MRCLM-2','Terrebonne - Mascouche',3);
insert into Services values (416,3,'MRCLM-20','Terrebonne - Mascouche',3);
insert into Services values (417,3,'MRCLM-21','Terrebonne - Mascouche',3);
insert into Services values (418,3,'MRCLM-22','Mascouche - Cité du sport - Cégep de Terrebonne',3);
insert into Services values (419,3,'MRCLM-23','Terrebonne - Sainte-Thérèse (Cégep Lionel-Groulx)',3);
insert into Services values (420,3,'MRCLM-24C','Terrebonne - Cité du sport - Cégep de Terrebonne',3);
insert into Services values (421,3,'MRCLM-25','Terrebonne - Montréal',3);
insert into Services values (422,3,'MRCLM-25B','Terrebonne - Montréal',3);
insert into Services values (423,3,'MRCLM-27','Terrebonne - Cité du Sport - Cégep de Terrebonne',3);
insert into Services values (424,3,'MRCLM-3','Terrebonne - Mascouche',3);
insert into Services values (425,3,'MRCLM-30','Gare Mascouche - Terrebonne - Terminus Radisson',3);
insert into Services values (426,3,'MRCLM-4','Terrebonne - Mascouche',3);
insert into Services values (427,3,'MRCLM-40','Lachenaie - Montréal - Terminus Radisson',3);
insert into Services values (428,3,'MRCLM-403','Mascouche - Gare Mascouche',3);
insert into Services values (429,3,'MRCLM-41','Terrebonne - Mascouche',3);
insert into Services values (430,3,'MRCLM-417','La Plaine - Gare Mascouche',3);
insert into Services values (431,3,'MRCLM-45','Terrebonne - Bois-des-Filion',3);
insert into Services values (432,3,'MRCLM-48','Terrebonne - secteur centre',3);
insert into Services values (433,3,'MRCLM-5','Terrebonne - Bois-des-Filion',3);
insert into Services values (434,3,'MRCLM-8','Terrebonne - secteur centre',3);
insert into Services values (435,3,'MRCLM-9','Terrebonne - secteur ouest',3);
insert into Services values (436,3,'OMITSJU-1','Sainte-Julie (Des Hauts-Bois)',3);
insert into Services values (437,3,'OMITSJU-3','Sainte-Julie (Principale)',3);
insert into Services values (438,3,'OMITSJU-325','Express Longueuil - Cégep',3);
insert into Services values (439,3,'OMITSJU-330','Express Longueuil - CFP - Cégep',3);
insert into Services values (440,3,'OMITSJU-340','Express Longueuil - Promenades Saint-Bruno',3);
insert into Services values (441,3,'OMITSJU-350','Express Longueuil',3);
insert into Services values (442,3,'OMITSJU-4','Sainte-Julie (Abbé-Théoret)',3);
insert into Services values (443,3,'OMITSJU-5','Sainte-Julie (N.P.-Lapierre)',3);
insert into Services values (444,3,'OMITSJU-600','Sainte-Julie - Terminus Brossard',3);
insert into Services values (445,3,'OMITSJU-8','Sainte-Julie (secteur nord)',3);
insert into Services values (446,3,'LRRS-134','Saint-Philippe - Candiac',3);
insert into Services values (447,3,'LRRS-140','La Prairie (Balmoral - Briqueterie - Magdeleine)',3);
insert into Services values (448,3,'LRRS-141','La Prairie (Magdeleine - Briqueterie -Balmoral)',3);
insert into Services values (449,3,'LRRS-142','Candiac (Montcalm - Fouquet - Haendel)',3);
insert into Services values (450,3,'LRRS-143','Candiac - La Prairie',3);
insert into Services values (451,3,'LRRS-144','La Prairie (Symbiocité)',3);
insert into Services values (452,3,'LRRS-146','Candiac (Deauville - Carrefour - Gare)',3);
insert into Services values (453,3,'LRRS-147','Candiac (Barcelone - Carrefour - Gare)',3);
insert into Services values (454,3,'LRRS-150','Sainte-Catherine (Brébeuf - Monchamp - Gare)',3);
insert into Services values (455,3,'LRRS-151','Delson (Principale Nord) - Sainte-Catherine',3);
insert into Services values (456,3,'LRRS-152','Delson (Principale Sud - Gare)',3);
insert into Services values (457,3,'LRRS-153','Saint-Constant (Saint-Pierre - Gare - Beauvais)',3);
insert into Services values (458,3,'LRRS-154','Sainte-Catherine (Marie-Victorin - Écluses)',3);
insert into Services values (459,3,'LRRS-155','Delson - Saint-Constant (Gare Sainte-Catherine )',3);
insert into Services values (460,3,'LRRS-156','Saint-Constant (SmartCentres - Monchamp - Gare)',3);
insert into Services values (461,3,'LRRS-450','La Prairie (Magdeleine) - Terminus Brossard',3);
insert into Services values (462,3,'LRRS-451','La Prairie (Briqueterie) - Terminus Brossard',3);
insert into Services values (463,3,'LRRS-452','La Prairie (Symbiocité-Briqueterie)-Term. Brossard',3);
insert into Services values (464,3,'LRRS-453','La Prairie (Vieux-La Prairie) - Terminus Panama',3);
insert into Services values (465,3,'LRRS-454','Candiac (Charlemagne) - Terminus Brossard',3);
insert into Services values (466,3,'LRRS-455','Candiac (Deauville) - Terminus Brossard',3);
insert into Services values (467,3,'LRRS-456','Candiac (Fouquet) - Terminus Brossard',3);
insert into Services values (468,3,'LRRS-457','Saint-Philippe - Terminus Brossard',3);
insert into Services values (469,3,'LRRS-458','La Prairie - Terminus Panama',3);
insert into Services values (470,3,'LRRS-459','Candiac - Terminus Panama',3);
insert into Services values (471,3,'LRRS-550','La Prairie - Longueuil (Cégep É.-Montpetit)',3);
insert into Services values (472,3,'LRRS-551','Candiac - Longueuil (Cégep É.-Montpetit)',3);
insert into Services values (473,3,'LRRS-552','Saint-Constant - Delson - Terminus Brossard',3);
insert into Services values (474,3,'LRRS-553','Sainte-Catherine - Delson - Terminus Panama',3);
insert into Services values (475,3,'LRRS-554','Delson - Terminus Brossard',3);
insert into Services values (476,3,'LRRS-555','Delson - Longueuil (Cégep É.-Montpetit)',3);
insert into Services values (477,3,'LRRS-556','Delson - Montréal (Angrignon - Cégep A-Laurendeau)',3);
insert into Services values (478,3,'LRRS-650','Delson - Candiac - La Prairie - Terminus Panama',3);
insert into Services values (479,3,'LRRS-651','Delson -Candiac -La Prairie-Term. Panama-Longueuil',3);
insert into Services values (480,4,'1','Desaulniers / Victoria / Windsor',3);
insert into Services values (481,4,'3','Secteur Laflèche',3);
insert into Services values (482,4,'4','Taschereau / Payer / DIX30',3);
insert into Services values (483,4,'5','Auteuil / mtée St-Hubert / Maisonneuve',3);
insert into Services values (484,4,'6','Victoria',3);
insert into Services values (485,4,'8','ch. Chambly / Cousineau / Promenades St-Bruno',3);
insert into Services values (486,4,'9','Secteurs L-M St-Hubert',3);
insert into Services values (487,4,'10','Roland-Therrien / Belcourt',3);
insert into Services values (488,4,'13','Riverside / Secteurs P-V Brossard',3);
insert into Services values (489,4,'14','Rome / DIX30',3);
insert into Services values (490,4,'15','Riverside / Alexandra / Churchill',3);
insert into Services values (491,4,'16','Nobert / Antoinette-Robidoux / Adoncour',3);
insert into Services values (492,4,'17','Roland-Therrien / Roberval',3);
insert into Services values (493,4,'19','Davis',3);
insert into Services values (494,4,'20','Jean-Paul-Vincent / Beauharnois',3);
insert into Services values (495,4,'21','Grande-Allée / du Quartier',3);
insert into Services values (496,4,'22','Gare Longueuil - St-Hubert/Sect. B Vieux-Longueuil',3);
insert into Services values (497,4,'23','Ste-Hélène / Jacques-Cartier',3);
insert into Services values (498,4,'25','Parcs industriels Vieux-Longueuil / Boucherville',3);
insert into Services values (499,4,'28','ch. Chambly / Savane / ENA',3);
insert into Services values (500,4,'29','Collectivité Nouvelle',3);
insert into Services values (501,4,'30','Secteurs P-V Brossard',3);
insert into Services values (502,4,'31','Secteurs R-S-T Brossard / St-Laurent',3);
insert into Services values (503,4,'32','Secteur B Brossard / Mountainview',3);
insert into Services values (504,4,'33','Secteurs M-N-O Brossard',3);
insert into Services values (505,4,'34','Secteur A Brossard / Bellevue',3);
insert into Services values (506,4,'37','Simard / du Béarn',3);
insert into Services values (507,4,'38','Chevrier / Secteur B Brossard',3);
insert into Services values (508,4,'41','Rome / Milan',3);
insert into Services values (509,4,'42','Gaétan-Boucher / Parc de la Cité',3);
insert into Services values (510,4,'43','Milan / Rome',3);
insert into Services values (511,4,'44','Secteurs M-N-O Brossard',3);
insert into Services values (512,4,'46','Secteurs R-S-T Brossard',3);
insert into Services values (513,4,'47','Secteurs R-S-T Brossard',3);
insert into Services values (514,4,'49','Secteurs R-S Brossard',3);
insert into Services values (515,4,'50','Bienville / Orchard / Prince-Charles',3);
insert into Services values (516,4,'54','Tiffin / St-Georges / Taschereau',3);
insert into Services values (517,4,'55','Victoria / Wellington',3);
insert into Services values (518,4,'59','Montgomery / Gareau',3);
insert into Services values (519,4,'60','Milan / Gaétan-Boucher / Promenades St-Bruno',3);
insert into Services values (520,4,'61','Boucherville / Terminus Radisson',3);
insert into Services values (521,4,'71','Curé-Poirier',3);
insert into Services values (522,4,'73','Joliette / de Lyon',3);
insert into Services values (523,4,'74','St-Laurent / Secteur Bellerive',3);
insert into Services values (524,4,'75','Quinn / Brébeuf',3);
insert into Services values (525,4,'76','Roland-Therrien / Roberval',3);
insert into Services values (526,4,'77','Taschereau / Coteau-Rouge / Cégep É.-Montpetit',3);
insert into Services values (527,4,'78','Adoncour / du Colisée',3);
insert into Services values (528,4,'80','De Montarville / Carrefour de la Rive-Sud',3);
insert into Services values (529,4,'81','du Fort-St-Louis / Marie-Victorin',3);
insert into Services values (530,4,'82','Marie-Victorin / du Fort-St-Louis',3);
insert into Services values (531,4,'83','De Montarville / Samuel-De Champlain',3);
insert into Services values (532,4,'84','Samuel-De Champlain / De Montarville',3);
insert into Services values (533,4,'85','Îles-Percées / de Mortagne / de Gascogne',3);
insert into Services values (534,4,'86','Samuel-De Champlain / De Montarville / TCV',3);
insert into Services values (535,4,'87','Marie-Victorin / du Fort St-Louis / TCV',3);
insert into Services values (536,4,'88','ch. Chambly / Mountainview',3);
insert into Services values (537,4,'93','Gare St-Bruno / Montarville / Y.-Duckett',3);
insert into Services values (538,4,'98','Parc industriel St-Bruno / Parent',3);
insert into Services values (539,4,'99','Promenades St-Bruno / Saint-Bruno-de-Montarville',3);
insert into Services values (540,4,'120','Fernand-Lafontaine / Stationnement de Mortagne',3);
insert into Services values (541,4,'123','Jacques-Cartier / Parcs industriels',3);
insert into Services values (542,4,'125','Pratt & Whitney / Lumenpulse',3);
insert into Services values (543,4,'128','Zone aéroportuaire / Parc industriel St-Bruno',3);
insert into Services values (544,4,'132','DIX30 / Parc de la Cité / Mountainview',3);
insert into Services values (545,4,'160','Milan / Gaétan-Boucher / Centre-ville St-Bruno',3);
insert into Services values (546,4,'161','R.-Therrien / J.-Cartier / De Montarville',3);
insert into Services values (547,4,'170','Station Papineau / Ste-Hélène / J.-Cartier',3);
insert into Services values (548,4,'180','De Montarville / des Sureaux',3);
insert into Services values (549,4,'185','Ampère / Gay-Lussac',3);
insert into Services values (550,4,'192','Terminus Brossard / Montarville / Y.-Duckett',3);
insert into Services values (551,4,'199','Seigneurial / Grand Boulevard',3);
insert into Services values (552,4,'214','Station Brossard / de Rome / St-Laurent',3);
insert into Services values (553,4,'284','Navette Boucherville',3);
insert into Services values (554,4,'299','SKIBUS et SÉPAQ Saint-Bruno',3);
insert into Services values (555,4,'410','Express Roland-Therrien / Belcourt',3);
insert into Services values (556,4,'417','Express Roland-Therrien / Roberval',3);
insert into Services values (557,4,'421','Grande-Allée / A.-Frappier',3);
insert into Services values (558,4,'428','Zone aéroportuaire / Agence spatiale canadienne',3);
insert into Services values (559,4,'442','Cousineau / Pacific',3);
insert into Services values (560,4,'461','Express de Touraine / de Montarville / Radisson',3);
insert into Services values (561,4,'462','Touraine-Mortagne-Radisson-HMR-Inst.cardio',3);
insert into Services values (562,4,'500','École Saint-Lambert International High School',3);
insert into Services values (563,4,'501','Écoles privées',3);
insert into Services values (564,4,'503','École Centennial Regional High School',3);
insert into Services values (565,4,'505','École Centennial Regional High School',3);
insert into Services values (566,4,'521','École Centennial Regional High School',3);
insert into Services values (567,4,'524','École Centennial Regional High School',3);
insert into Services values (568,4,'525','École Centennial Regional High School',3);
insert into Services values (569,4,'526','École Centennial Regional High School',3);
insert into Services values (570,4,'530','École Centennial Regional High School',3);
insert into Services values (571,4,'532','École Centennial Regional High School',3);
insert into Services values (572,4,'533','École Centennial Regional High School',3);
insert into Services values (573,4,'534','École Centennial Regional High School',3);
insert into Services values (574,4,'535','École Centennial Regional High School',3);
insert into Services values (575,4,'536','École Centennial Regional High School',3);
insert into Services values (576,4,'538','École Heritage Regional High School',3);
insert into Services values (577,4,'539','École Heritage Regional High School',3);
insert into Services values (578,4,'540','École Heritage Regional High School',3);
insert into Services values (579,4,'542','École Heritage Regional High School',3);
insert into Services values (580,4,'544','École Centennial Regional High School',3);
insert into Services values (581,4,'546','École Centennial Regional High School',3);
insert into Services values (582,4,'547','École Centennial Regional High School',3);
insert into Services values (583,4,'549','École Centennial Regional High School',3);
insert into Services values (584,4,'550','École Centennial Regional High School',3);
insert into Services values (585,4,'551','École Centennial Regional High School',3);
insert into Services values (586,4,'565','École Saint-Lambert International High School',3);
insert into Services values (587,4,'570','École Saint-Lambert International High School',3);
insert into Services values (588,4,'572','École Saint-Lambert International High School',3);
insert into Services values (589,4,'575','École Saint-Lambert International High School',3);
insert into Services values (590,4,'580','École Saint-Lambert International High School',3);
insert into Services values (591,4,'600','Écoles privées',3);
insert into Services values (592,4,'601','École de l''Agora',3);
insert into Services values (593,4,'602','École de l''Agora',3);
insert into Services values (594,4,'604','École de l''Agora',3);
insert into Services values (595,4,'605','École de l''Agora',3);
insert into Services values (596,4,'606','Écoles privées',3);
insert into Services values (597,4,'607','École de l''Agora',3);
insert into Services values (598,4,'608','École André-Laurendeau et Cégep Édouard-Montpetit',3);
insert into Services values (599,4,'609','École de l''Agora',3);
insert into Services values (600,4,'613','Écoles privées',3);
insert into Services values (601,4,'614','Écoles privées',3);
insert into Services values (602,4,'616','École Gérard-Filion',3);
insert into Services values (603,4,'618','Écoles privées',3);
insert into Services values (604,4,'620','Collège Français',3);
insert into Services values (605,4,'624','École St-Jean-Baptiste',3);
insert into Services values (606,4,'640','École Antoine-Brossard',3);
insert into Services values (607,4,'644','École Antoine-Brossard',3);
insert into Services values (608,4,'650','École Antoine-Brossard',3);
insert into Services values (609,4,'653','École Antoine-Brossard',3);
insert into Services values (610,4,'656','École Antoine-Brossard',3);
insert into Services values (611,4,'660','École Antoine-Brossard',3);
insert into Services values (612,4,'664','École Antoine-Brossard',3);
insert into Services values (613,4,'665','École Antoine-Brossard',3);
insert into Services values (614,4,'670','École Antoine-Brossard',3);
insert into Services values (615,4,'671','École Jacques-Rousseau',3);
insert into Services values (616,4,'672','École Jacques-Rousseau',3);
insert into Services values (617,4,'673','École Jacques-Rousseau',3);
insert into Services values (618,4,'674','École Antoine-Brossard',3);
insert into Services values (619,4,'675','École Jacques-Rousseau',3);
insert into Services values (620,4,'676','École Jacques-Rousseau',3);
insert into Services values (621,4,'678','École Jacques-Rousseau',3);
insert into Services values (622,4,'683','Cégep Édouard-Montpetit',3);
insert into Services values (623,4,'684','École Antoine-Brossard',3);
insert into Services values (624,4,'689','École Antoine-Brossard',3);
insert into Services values (625,4,'690','École Antoine-Brossard',3);
insert into Services values (626,4,'691','École Lucille-Teasdale',3);
insert into Services values (627,4,'692','École Lucille-Teasdale',3);
insert into Services values (628,4,'693','École Lucille-Teasdale',3);
insert into Services values (629,4,'694','École Lucille-Teasdale',3);
insert into Services values (630,4,'695','École Lucille-Teasdale',3);
insert into Services values (631,4,'696','École Lucille-Teasdale',3);
insert into Services values (632,4,'697','École Lucille-Teasdale - Secteur Chevrier',3);
insert into Services values (633,5,'12','Pont-Viau / Métro Cartier',3);
insert into Services values (634,5,'144','Métro Côte-Vertu / Sainte-Dorothée',3);
insert into Services values (635,5,'151','Sainte-Rose / Métro Côte-Vertu',3);
insert into Services values (636,5,'16','Métro Montmorency / Laval-des-Rapides / Armand-Frappier',3);
insert into Services values (637,5,'17','Auteuil / Métro Cartier',3);
insert into Services values (638,5,'2','Métro Henri-Bourassa / Métro Montmorency',3);
insert into Services values (639,5,'20','Métro Cartier / Chomedey',3);
insert into Services values (640,5,'22','Saint-François / Métro Cartier',3);
insert into Services values (641,5,'222','Saint-Vincent-De-Paul / Métro Cartier',3);
insert into Services values (642,5,'24','Métro Cartier / Sainte-Dorothée',3);
insert into Services values (643,5,'252','Saint-François / Métro Henri-Bourassa',3);
insert into Services values (644,5,'26','Métro Montmorency / Gare Sainte-Dorothée',3);
insert into Services values (645,5,'27','Gare Vimont / Métro Cartier',3);
insert into Services values (646,5,'31','Auteuil / Métro Henri-Bourassa',3);
insert into Services values (647,5,'313','Chomedey / Métro Côte-Vertu',3);
insert into Services values (648,5,'33','Métro Montmorency / Métro Cartier',3);
insert into Services values (649,5,'345','Gare Vimont / Métro Henri-Bourassa',3);
insert into Services values (650,5,'36','Métro Montmorency / Chomedey',3);
insert into Services values (651,5,'360','Chomedey',3);
insert into Services values (652,5,'37','Sainte-Rose / Métro Cartier',3);
insert into Services values (653,5,'39','Auteuil / Terminus Le Carrefour',3);
insert into Services values (654,5,'40','Métro Montmorency / Chomedey',3);
insert into Services values (655,5,'41','Auteuil / Métro Cartier',3);
insert into Services values (656,5,'42','Saint-François / Terminus Le Carrefour',3);
insert into Services values (657,5,'43','Auteuil / Métro Cartier',3);
insert into Services values (658,5,'45','Auteuil / Métro Montmorency',3);
insert into Services values (659,5,'46','Laval-Ouest / Métro Montmorency',3);
insert into Services values (660,5,'48','Gare Vimont / Métro Cartier',3);
insert into Services values (661,5,'50','Saint-Vincent-De-Paul / Terminus Le Carrefour',3);
insert into Services values (662,5,'52','Saint-François / Métro Henri-Bourassa',3);
insert into Services values (663,5,'55','Laval-Ouest / Métro Henri-Bourassa',3);
insert into Services values (664,5,'56','Métro Montmorency / Sainte-Dorothée',3);
insert into Services values (665,5,'58','Saint-Vincent-De-Paul / Métro Cartier',3);
insert into Services values (666,5,'60','Métro Cartier / Chomedey',3);
insert into Services values (667,5,'61','Fabreville / Métro Montmorency',3);
insert into Services values (668,5,'63','Gare Sainte-Rose / Métro Cartier',3);
insert into Services values (669,5,'65','Gare Sainte-Rose / Métro Montmorency',3);
insert into Services values (670,5,'66','Terminus Le Carrefour / Sainte-Dorothée',3);
insert into Services values (671,5,'70','Métro Cartier / Métro Montmorency',3);
insert into Services values (672,5,'713','Sainte-Dorothée / Métro Côte-Vertu',3);
insert into Services values (673,5,'73','Fabreville / Métro Cartier',3);
insert into Services values (674,5,'730','Gare Sainte-Dorothée / Montréal',3);
insert into Services values (675,5,'74','Saint-François / Métro Cartier',3);
insert into Services values (676,5,'744','Métro Côte-Vertu / Gare Sainte-Dorothée',3);
insert into Services values (677,5,'76','Métro Montmorency / Gare Sainte-Dorothée',3);
insert into Services values (678,5,'901','Saint-François / Métro Cartier',3);
insert into Services values (679,5,'902','Terminus Le Carrefour / Métro Côte-Vertu',3);
insert into Services values (680,5,'903','Gare Sainte-Dorothée / Métro Montmorency',3);
insert into Services values (681,5,'925','Saint-François / Métro Radisson',3);
insert into Services values (682,5,'942','Saint-François / Métro Montmorency',3);
insert into Services values (683,6,'A1','Branche principale',2);
