create table MunicipalSectors (
ms_ID integer primary key not null,
r_ID integer not null constraint fk_ms_r_ID references Regions (regionID),
name varchar(300) not null
);

insert into MunicipalSectors values (101,1,'MontrÈal : Centre-ville');
insert into MunicipalSectors values (102,1,'MontrÈal : Centre-ville pÈriphÈrique');
insert into MunicipalSectors values (103,2,'MontrÈal : Sud-Ouest');
insert into MunicipalSectors values (104,2,'MontrÈal : Notre-Dame-de-Gr‚ce');
insert into MunicipalSectors values (105,2,'MontrÈal : CÙte-des-Neiges');
insert into MunicipalSectors values (106,2,'MontrÈal : Plateau Mont-Royal');
insert into MunicipalSectors values (107,2,'MontrÈal : Villeray');
insert into MunicipalSectors values (108,2,'MontrÈal : Ahuntsic');
insert into MunicipalSectors values (109,2,'MontrÈal : Saint-Michel');
insert into MunicipalSectors values (110,2,'MontrÈal : Rosemont');
insert into MunicipalSectors values (111,2,'MontrÈal : Sud-Est');
insert into MunicipalSectors values (112,2,'MontrÈal : Mercier');
insert into MunicipalSectors values (120,2,'Mont-Royal');
insert into MunicipalSectors values (121,2,'MontrÈal : Outremont');
insert into MunicipalSectors values (122,2,'Westmount');
insert into MunicipalSectors values (123,2,'Hampstead');
insert into MunicipalSectors values (142,2,'MontrÈal : Verdun (Verdun)');
insert into MunicipalSectors values (143,2,'MontrÈal : Verdun (Œle des soeurs)');
insert into MunicipalSectors values (113,3,'MontrÈal : Pointe-aux-Trembles');
insert into MunicipalSectors values (114,3,'MontrÈal : RiviËre-des-Prairies');
insert into MunicipalSectors values (115,3,'MontrÈal-Est');
insert into MunicipalSectors values (116,3,'MontrÈal : Anjou');
insert into MunicipalSectors values (117,3,'MontrÈal : Saint-LÈonard');
insert into MunicipalSectors values (118,3,'MontrÈal : MontrÈal-Nord');
insert into MunicipalSectors values (119,4,'MontrÈal : Saint-Laurent');
insert into MunicipalSectors values (124,4,'CÙte-Saint-Luc');
insert into MunicipalSectors values (125,4,'MontrÈal-Ouest');
insert into MunicipalSectors values (126,4,'MontrÈal : Saint-Pierre');
insert into MunicipalSectors values (128,4,'MontrÈal : LaSalle');
insert into MunicipalSectors values (129,4,'MontrÈal : Lachine');
insert into MunicipalSectors values (130,4,'Dorval, L''Œle-Dorval');
insert into MunicipalSectors values (131,4,'Pointe-Claire');
insert into MunicipalSectors values (132,4,'Dollard-Des Ormeaux');
insert into MunicipalSectors values (133,4,'MontrÈal : Roxboro');
insert into MunicipalSectors values (134,4,'MontrÈal : L''Œle-Bizard');
insert into MunicipalSectors values (135,4,'MontrÈal : Sainte-GeneviËve');
insert into MunicipalSectors values (136,4,'MontrÈal : Pierrefonds');
insert into MunicipalSectors values (137,4,'Kirkland');
insert into MunicipalSectors values (138,4,'Beaconsfield');
insert into MunicipalSectors values (139,4,'Baie-D''UrfÈ');
insert into MunicipalSectors values (144,4,'Senneville-Sainte-Anne-de-Bellevue');
insert into MunicipalSectors values (301,5,'Longueuil : Vieux-Longueuil');
insert into MunicipalSectors values (302,5,'Longueuil : Longueuil Est');
insert into MunicipalSectors values (303,5,'Longueuil : De Lyon');
insert into MunicipalSectors values (304,5,'Saint-Lambert');
insert into MunicipalSectors values (305,5,'Longueuil : LeMoyne');
insert into MunicipalSectors values (306,5,'Longueuil : Greenfield Park');
insert into MunicipalSectors values (307,5,'Longueuil : Saint-Hubert');
insert into MunicipalSectors values (308,5,'Brossard');
insert into MunicipalSectors values (309,5,'Boucherville');
insert into MunicipalSectors values (310,5,'Saint-Bruno-de-Montarville');
insert into MunicipalSectors values (401,6,'Laval : Ouest');
insert into MunicipalSectors values (402,6,'Laval : Sainte-DorothÈe, Laval-sur-le-lac');
insert into MunicipalSectors values (403,6,'Laval : Chomedey');
insert into MunicipalSectors values (404,6,'Laval : Sainte-Rose, Fabreville');
insert into MunicipalSectors values (405,6,'Laval : Vimont, Auteuil');
insert into MunicipalSectors values (406,6,'Laval : Pont-Viau, Laval-des-Rapides');
insert into MunicipalSectors values (407,6,'Laval : Duvernay, Saint-Vincent-de-Paul');
insert into MunicipalSectors values (408,6,'Laval : Saint-FranÁois');
insert into MunicipalSectors values (601,7,'Lavaltrie, Lanoraie');
insert into MunicipalSectors values (602,7,'Crabtree, Joliette, Notre-Dame-des-Prairies, St-Charles-BorromÈe, St-Paul, St-Pierre, St-Thomas');
insert into MunicipalSectors values (611,7,'Repentigny, Charlemagne');
insert into MunicipalSectors values (612,7,'L''Assomption, Saint-Sulpice, L''…êpiphanie (V), L''ê…piphanie (P)');
insert into MunicipalSectors values (621,7,'Terrebonne : Lachenaie');
insert into MunicipalSectors values (622,7,'Terrebonne : Terrebonne (ex-municipalitÈ)');
insert into MunicipalSectors values (623,7,'Mascouche');
insert into MunicipalSectors values (624,7,'Terrebonne : La Plaine');
insert into MunicipalSectors values (631,7,'Saint-Eustache');
insert into MunicipalSectors values (632,7,'Deux-Montagnes');
insert into MunicipalSectors values (633,7,'Pointe-Calumet, Saint-Joseph-du-Lac, Oka, Sainte-Marthe-sur-le-lac, Saint-Placide');
insert into MunicipalSectors values (641,7,'Boisbriand');
insert into MunicipalSectors values (642,7,'Sainte-ThÈrËse');
insert into MunicipalSectors values (643,7,'Blainville');
insert into MunicipalSectors values (644,7,'Lorraine, Bois-des-Filion, Rosemere');
insert into MunicipalSectors values (645,7,'Sainte-Anne-des-Plaines');
insert into MunicipalSectors values (651,7,'Mirabel');
insert into MunicipalSectors values (661,7,'Saint-JÈrÙme');
insert into MunicipalSectors values (662,7,'Saint-Colomban');
insert into MunicipalSectors values (663,7,'Sainte-Sophie, PrÈvost, Saint-Hippolyte');
insert into MunicipalSectors values (671,7,'Saint-Roch-de-l''Achigan, Saint-Roch-Ouest, Saint-Lin-Laurentides, Saint-Calixte, Sainte-Julienne');
insert into MunicipalSectors values (672,7,'St-Alexis (V), St-Alexis (P), Ste-Marie-SalomÇ, St-Esprit, St-Jacques, St-Liguori');
insert into MunicipalSectors values (673,7,'Rawdon');
insert into MunicipalSectors values (681,7,'Lachute, Browsburg-Chatham, Saint-AndrÈ-d''Argenteuil, Wentworth, Gore, Mille-Isles');
insert into MunicipalSectors values (691,7,'Saint-Sauveur, Piedmont, Sainte-AdÈle, Morin-Heights, Saint-Adolphe-d''Howard, Sainte-Anne-des-Lacs, Wentworth-Nord, Lac-des-Seizes-Œles');
insert into MunicipalSectors values (501,8,'Richelieu, Saint-Mathias-sur-Richelieu');
insert into MunicipalSectors values (502,8,'Marieville');
insert into MunicipalSectors values (511,8,'Saint-Jean-sur-Richelieu');
insert into MunicipalSectors values (521,8,'Carignan, Chambly');
insert into MunicipalSectors values (522,8,'Saint-Basile-le-Grand');
insert into MunicipalSectors values (523,8,'Beloeil, Saint-Mathieu-de-Beloeil, McMasterville');
insert into MunicipalSectors values (524,8,'Mont-Saint-Hilaire, Otterburn Park, Saint-Jean-Baptiste');
insert into MunicipalSectors values (525,8,'Saint-Charles-sur-Richelieu, Saint-Marc-sur-Richelieu, Saint-Antoine-sur-Richelieu, Saint-Denis-sur-Richelieu');
insert into MunicipalSectors values (531,8,'Saint-Amable, Sainte-Julie');
insert into MunicipalSectors values (532,8,'VerchËres, Calixa-LavallÈe, Varennes, Contrecoeur');
insert into MunicipalSectors values (533,8,'St-Joseph-de-Sorel, St-Roch-de-Richelieu, Sorel-Tracy');
insert into MunicipalSectors values (541,8,'Saint-Philippe, Saint-Mathieu');
insert into MunicipalSectors values (542,8,'La Prairie');
insert into MunicipalSectors values (543,8,'Candiac');
insert into MunicipalSectors values (544,8,'Sainte-Catherine, Saint-Constant, Delson');
insert into MunicipalSectors values (545,8,'Mercier, Saint-Isidore');
insert into MunicipalSectors values (546,8,'Ch‚teauguay, LÈry');
insert into MunicipalSectors values (547,8,'Kahnawake');
insert into MunicipalSectors values (551,8,'Saint-êdouard, Saint-Michel, Saint-RÈmi, Saint-Patrice-de-Sherrington, Saint-Jacques-le-Mineur');
insert into MunicipalSectors values (561,8,'Beauharnois');
insert into MunicipalSectors values (562,8,'Salaberry-de-Valleyfield');
insert into MunicipalSectors values (563,8,'Saint-ê…tienne-de-Beauharnois, Saint-Louis-de-Gonzague, Saint-Stanislas-de-Kostka');
insert into MunicipalSectors values (564,8,'Sainte-Martine, Saint-Urbain-Premier');
insert into MunicipalSectors values (571,8,'Les Coteaux, Coteau-du-Lac, Saint-Clet, Les CËdres, Pointe-des-Cascades');
insert into MunicipalSectors values (572,8,'Notre-Dame-de-l''Œle-Perrot, Pincourt, Terrasse-Vaudreuil, L''Œle-Perrot');
insert into MunicipalSectors values (573,8,'Vaudreuil-Dorion, Vaudreuil-sur-le-Lac, L''Œle-Cadieux');
insert into MunicipalSectors values (574,8,'Hudson, Saint-Lazare');
insert into MunicipalSectors values (575,8,'Rigaud, Pointe-Fortune');
insert into MunicipalSectors values (576,8,'RiviËre-Beaudette, Saint-Polycarpe, Saint-TÈlesphore, Saint-Zotique, Sainte-Justine-de-Newton, Sainte-Marthe, TrËs-Saint-RÈdempteur');
